In [0]:

df = spark.read.parquet("s3://b2c-prod-data-pipeline-qa/fredric_localized_sample_apps/")
df.createOrReplaceTempView("localized_detail_sample")


# Android iOS
sql = '''
    select distinct platform,locale
        from localized_detail_sample
'''

df_raw_locale = spark.sql(sql)

count = df_raw_locale.count() 
df_raw_locale.show(count)

print(count)

In [0]:
%%sh

aws s3 ls s3://aardvark-prod-dca-data/interface/localized_app_detail/date=2021-07-25/platform=Android/

In [0]:

## Convert raw data to wide table

from  pyspark.storagelevel import StorageLevel
from pyspark.sql.functions import *

df = spark.read.parquet("s3://aardvark-prod-dca-data/interface/localized_app_detail/")

df.createOrReplaceTempView("raw_data")

raw_to_wide = '''

SELECT  date,
        country,
        app_id,
        platform,
        bundle_id,
        app_store_notes, banner_image_url, banner_md5, code, company_code, company_id, company_name, company_slug, release_date as current_release_date, description, features, first_release_date, icon_url, icon_md5, language_code, languages, replace(locale, '_', '-') as locale, name, permissions, coalesce(cast(price as  float),0.0) as price, primary_category_code, primary_category_id, promotional_text, release_notes, screenshots_json, screenshots_md5, file_size as size, slug, subtitle, version, status
    FROM raw_data  PIVOT (FIRST(value)
      FOR field_name IN ('app_store_notes', 'banner_image_url', 'banner_md5', 'code' ,'company_code', 'company_id', 'company_name', 'company_slug', 'release_date', 'description', 'features', 'first_release_date', 'icon_url', 'icon_md5', 'language_code', 'languages', 'locale', 'name', 'permissions', 'price', 'primary_category_code', 'primary_category_id', 'promotional_text', 'release_notes', 'screenshots_json', 'screenshots_md5', 'file_size', 'slug', 'subtitle', 'version', 'status')) where (date>='2021-08-11' and date<='2021-08-15')
'''
df = spark.sql(raw_to_wide)
df.write.parquet("s3://b2c-prod-data-pipeline-qa/fredric_localized1")

In [0]:
%%sh

# aws s3 ls s3://b2c-prod-data-pipeline-qa


aws configure get aws_access_key_id

In [0]:


postgres_df = (spark.read
  .format("jdbc")
  .option("url", "jdbc:postgresql://udw-aurora-prod.cluster-ro-crlexxwtzodp.us-east-1.rds.amazonaws.com:5432/aa_intelligence_production")
  .option("dbtable", "")
  .option("user", "app_aurora_bdp_qa")
  .option("password", "9KRMPySxvw9elJqk")
  .load())

postgres_df.show(10, False)

In [0]:

df = spark.read.parquet("s3://aardvark-prod-dca-data/fact/MKT_AD_REVENUE/version=1.0.0/range_type=WEEK/")
df.createOrReplaceTempView("localized_detail_sample")


# Android iOS
sql = '''
    select *
        from localized_detail_sample
'''

df_raw_locale = spark.sql(sql)

count = df_raw_locale.count() 
df_raw_locale.show(count)

print(count)

In [0]:
%%sh