In [0]:
%%sh
aws s3 ls  s3://b2c-prod-dca-store-estimates/iap_revenue/date=2021-11-14/report_type=FINAL/

In [0]:


# +----------+------------+--------------------+--------------------+--------------+------------------+--------------------+------------------+--------------------+--------------+
# |    app_id|country_code|                 sku|           sku_title|customer_price|   est_iap_revenue|est_iap_revenue_perc|       est_iap_vol|    est_iap_vol_perc|isSubscription|
# +----------+------------+--------------------+--------------------+--------------+------------------+--------------------+------------------+--------------------+--------------+
# |1542926387|          AU|com.bingo.wild.fr...|  Mini Powerup Pack!|          2.99| 5.865339599848072|0.057503329410275215|3.8942323969389694| 0.19275203909771396|         false|
# |1091986022|          JP|   jp.iinee.ios00001|    120pt(200円お得)|        1220.0| 865.4686386431016| 0.45503082999111544|116.87846558325255|  0.7992089129630914|         false|
# | 922208952|          GB|        Monthly_1999|Course Hero Subsc...|         19.49| 24.60742322767157| 0.12181892686966124|1.3521583365780436| 0.14190619022079265|          true|
# |1442673273|          FR|          premiumsms|         Send by SMS|          0.99| 2.185312976036535| 0.07049396696892048|  2.81463581199753|  0.1154981559674155|         false|
# | 830286763|          AU|com.isd.retouchme...|80 credits in Pho...|          4.49| 26.35906212642186| 0.21430131810099073|11.654227829003359| 0.10523507011953347|         false|


# path = "s3://b2c-prod-dca-store-estimates/iap_revenue/date=2021-11-24/report_type=FINAL/"
# spark.read.parquet(path).createOrReplaceTempView("test")


# df = spark.sql("select * from test where sku_title like '3280 Genesis Crystals' and country_code='US' ")
df = spark.sql("select  sum(est_iap_revenue) from test where app_id in ('284882215','1517783697') and country_code='US' ")

df.show()